spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

  ## redis 설정
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

# jwt 토큰 관련 값
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expiration-seconds: ${ACCESS_EXPIRATION_SECONDS}
  refresh-expiration-seconds: ${REFRESH_EXPIRATION_SECONDS}

images:
  patient: ${PATIENT_IMAGE}
  doctor: ${DOCTOR_IMAGE}
  center: ${CENTER_IMAGE}

# 쿼리문 파라미터 바인딩 값 확인
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

#custom swagger url
springdoc:
  swagger-ui:
    path: /swagger-ui.html

#FCM
google:
  fcm:
    service:
      secret: ${GOOGLE_FCM_SERVICE_SECRET}
      projectId: ${GOOGLE_FCM_SERVICE_PROJECTID}

